lakehouse_retail:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: dbt
      password: dbt
      port: 5432
      dbname: warehouse
      schema: public
      threads: 2